### ISSUE TITLE
Add scene-called events to in node on Light Groups

### ISSUE THREAD

**Issue by trilu2000** [deconz-community/node-red-contrib-deconz#103]
deconz-input delivers a message only on state change, is there an option/posibility to get messages also on scene change for a dedicated group of lights?

**Comment by CheariX** [comment]
I can confirm this behavior. I can also see scene change events using the `deconz-event` node, bit I expected the `deconz-input` to also fire.

**Comment by Zehir** [comment]
Did you select the group of lights in the `in` node or one member of the group ?
You can use the `deconz-event` node to look for `scene-called` events.

**Comment by CheariX** [comment]
I tried it with the `in` node and configured a group on it. It does not receive any event on calling a scene.
I can use the `deconz-even` node, then I get something like this:

`{"e":"scene-called","gid":"6","r":"scenes","scid":"2","t":"event"}`

This is not really handy, because I need to map `gid`and `scid` to some usefull information.

**Comment by VaskoJiri** [comment]
I have same issue. I have Aqara switch and group of aqara lights. When I set the lights, IN node dont work. But when i set IN node only to one of these lights, it works.
![165073549_739156403450338_2511562613821747749_n](https://user-images.githubusercontent.com/81432866/112661156-8125c580-8e56-11eb-853a-5ef465734056.png)

**Comment by Zehir** [comment]
> I have same issue. I have Aqara switch and group of aqara lights. When I set the lights, IN node dont work. But when i set IN node only to one of these lights, it works. ![165073549_739156403450338_2511562613821747749_n](https://user-images.githubusercontent.com/81432866/112661156-8125c580-8e56-11eb-853a-5ef465734056.png)

This is because the homekit format can only handle devices and node group of devices.

**Comment by Zehir** [comment]
I added in version [2.0.0-beta.13](https://www.npmjs.com/package/node-red-contrib-deconz/v/2.0.0-beta.13) a new way to have scene call msgs on the input node.
