### ISSUE TITLE
Conection Problem 

### ISSUE THREAD

**Issue by syswombat** [deconz-community/node-red-contrib-deconz#105]
** Describe issue **
i have Problem at

Edit deconz-server node
Name, ip, port, websocket port is added

i do activate the Gateway App conection

but on node Red still the magick button is not working.
it say i haven pressed the App Button in the gateway.
Is there another way to get this number

maybe with comandLine on the Raspberry Pi / RaspBee II itself?

hope on a feedback

have a nice day
vinc
** Your flow here **
Export your flow in json 

** Screens / Logs **

** Hardware / Software **
  - raspberry 4   
  - version of deconz gateway: 2.7.1 / 14.9.2020   26610700
  - version of node-red-contrib-deconz: 1.2.

**Comment by Zehir** [comment]
Did you use phoscon to open the gateway ?

**Comment by Zehir** [comment]
No answer from user
