### ISSUE TITLE
Unable to control "special" lights, like Heiman HS2WD-E

### ISSUE THREAD

**Issue by FlorianK84** [deconz-community/node-red-contrib-deconz#108]
**Problem**
Some zigbee devices are recognized as "lights" in Phoscon/deConz, like the Heiman siren HS2WD-E. This device doesn't have an "on"-attribute, it accepts only "alert". Setting "alert" to value "select" to activate the siren results in an error: 

> parameter, on, not available

**Solution**
To solve this problem I added the following code in nodes/out.js, line 160 (before `else if (command != 'scene') { // scene doesn't have a post payload, so keep it empty.`):

```
}else if (command == 'alert'){ // Heiman siren doesn't have a command "on" > just send the alert...
       post[command] = payload;
}
```

**Comment by Zehir** [comment]
Clean up issues, this is now in #130.
