### ISSUE TITLE
'Complete state payload' isn't "complete"

### ISSUE THREAD

**Issue by oywino** [deconz-community/node-red-contrib-deconz#109]
@andreypopov The ELKO Thermostat could be paired with the ConBee II gateway using Phoscon, and it did show up in deConz with all attributes available, but it never showed up in Phoscon (even though Phoscon successfully did the pairing).

However, the state pulldown list in your Get Node only presented some of the available attributes.

If I recall correctly, you said that your Node-Red palette extension depended on the sensor being present in the Phoscon app in order to make all attributes visible/accessible through your nodes.

So consequently, I posted a Pull Request over in the Phoscon-app-beta repository asking for support to get this fixed.
Well, now this is fixed - and the ELKO Thermostat is fully visible in Phoscon ;

![image](https://user-images.githubusercontent.com/18447119/103239636-7be7d600-494e-11eb-8774-cdd8e31d4cbf.png)

But your Get node still only shows some of the attributes.

![image](https://user-images.githubusercontent.com/18447119/103239415-bac95c00-494d-11eb-847d-79a5c1d91d42.png)

 Why is that ?

**Comment by Zehir** [comment]
You don't really to update phoscon if the rest api is updated. This plugin use the same as phoscon does so if it's displayed in phoscon you should be able to see it here too. Whate attributes is missing ?

**Comment by oywino** [comment]
Well, this is what the REST-API reveals:
```
{
    "config": {
        "heatsetpoint": 1700,
        "locked": null,
        "mode": "heat",
        "offset": 0,
        "on": true,
        "reachable": true,
        "schedule": {},
        "schedule_on": null,
        "temperaturemeasurement": "floor sensor"
    },
    "ep": 1,
    "etag": "c1cee46b6df5463bc18c7b50cb53bf7b",
    "lastseen": "2020-11-15T21:06Z",
    "manufacturername": "ELKO",
    "modelid": "Super TR",
    "name": "ELKO Termostat",
    "state": {
        "floortemperature": 1710,
        "heating": true,
        "lastupdated": "2020-11-15T21:06:58.731",
        "on": true,
        "temperature": 2810
    },
    "type": "ZHAThermostat",
    "uniqueid": "00:0d:6f:00:0e:9d:c6:46-01-0201"
}
```

**Comment by Zehir** [comment]
OK I see it's because he return only the state object and not the config one. I will do something to fix that. Maybe in #120.

**Comment by oywino** [comment]
Great 👍

**Comment by Zehir** [comment]
I added that part to the UI, it's will be fixed in #120

**Comment by oywino** [comment]
Excellent 😊
Thank you for the update.

**Comment by Zehir** [comment]
Clean up issues, this is now in #130.
