### ISSUE TITLE
Node Red - "inject Node" for Brightness/ColorTemp for lidl bulb

### ISSUE THREAD

**Issue by syswombat** [deconz-community/node-red-contrib-deconz#112]
** Describe your idea here**
Node Red - "inject Node" for Brightness/ColorTemp for lidl bulb

Color temperature light | _TZ3000_49qchf10 | TS0502A 
Hersteller: OWIM Gmbh
Model No.: HG06492C

I can't find out how to config a default  "inject Node" to change the bulb.

Thanks for a feedback
have a nice day
vinc

**Comment by Zehir** [comment]
Did you find a solution ?
What is the version of deconz you using ?
