### ISSUE TITLE
Disable/Enable Motion sensor

### ISSUE THREAD

**Issue by Tscherno** [deconz-community/node-red-contrib-deconz#115]
It seems currently not possible to disable a motion sensor via NodeRed. That would make more complex automations possible (for example don't turn light on if i watch TV, because that only can be the cat...). I know that it is possible via API because HUE Essentials can do it via the app.

**Comment by Zehir** [comment]
How he detect if the TV is on ?

**Comment by Tscherno** [comment]
Plex, LG, Energy Monitor.

**Comment by Zehir** [comment]
Ok I see the problem, you can use the command `on = false` on some sensors but they don't show up in the `out` node.

**Comment by Zehir** [comment]
Clean up issues, this is now in #130.
