### ISSUE TITLE
New version 1.3.0 adds not wanted "transistiontime" to payload

### ISSUE THREAD

**Issue by steff75** [deconz-community/node-red-contrib-deconz#118]
** Describe issue **
When sending a payload to a deconz-out node as a json object: **{"lift":50}**, the transistiontime parameter is also unwantedly appended.
Since the devices to be controlled are roller blinds that do not support the transistiontime parameter, only an error message is output:
`deconz-out ERROR: parameter, transitiontime, not available`

The old versions of node-red-contrib-deconz did not do this and the control operation was performed properly. 

** Your flow here **
Example flow
`[{"id":"bbcc3a76.0b9e78","type":"inject","z":"e6bdcf44.09a93","name":"lift 50 %","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"50","payloadType":"num","x":640,"y":3640,"wires":[["7a3cd15f.84fe3"]]},{"id":"7a3cd15f.84fe3","type":"rbe","z":"e6bdcf44.09a93","name":"","func":"rbe","gap":"","start":"","inout":"out","property":"payload","x":660,"y":3680,"wires":[["e1d94a40.71a9c8"]]},{"id":"e1d94a40.71a9c8","type":"change","z":"e6bdcf44.09a93","name":"","rules":[{"t":"move","p":"payload","pt":"msg","to":"payload.lift","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":830,"y":3680,"wires":[["4f1ab0f3.f353d","d762d699.369db8"]]},{"id":"d762d699.369db8","type":"deconz-output","z":"e6bdcf44.09a93","name":"Rollo 1","server":"feccbf1b.b8846","device":"d0:cf:5e:ff:fe:f5:7a:9a-01","device_name":"IKEA Rollo 1 [9] : Window covering device","command":"json","commandType":"object","payload":"payload","payloadType":"msg","transitionTime":"","x":1090,"y":3680,"wires":[]},{"id":"4f1ab0f3.f353d","type":"debug","z":"e6bdcf44.09a93","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":1100,"y":3640,"wires":[]},{"id":"feccbf1b.b8846","type":"deconz-server","name":"deCONZ","ip":"192.168.178.31","port":"8077","ws_port":"8078","secure":false,"polling":"15"}]`

** Screens / Logs **
![Bildschirmfoto 2021-02-20 um 13 28 01](https://user-images.githubusercontent.com/19283026/108596041-bab07000-7382-11eb-9827-d8aac9b60f95.png)
![Bildschirmfoto 2021-02-20 um 13 29 20](https://user-images.githubusercontent.com/19283026/108596056-e16ea680-7382-11eb-881c-2fe2459f4772.png)

** Hardware / Software **
  - Diskstation 218+, node-red official docker (v1.2.9) + marthoc/docker-deconz (v2.10.0)   
  - version of deconz gateway: [2.10.00] 
  - version of node-red-contrib-deconz: [1.3.0]

**Comment by Zehir** [comment]
This is fixed in 1.3.1, you will be able to see in less than an hour due to the way node-red handles updates.
Thanks for report.

**Comment by steff75** [comment]
Wow, very fast bug fix. Thanks!
