### ISSUE TITLE
Lights group to report brightness and temperature instead of "all_on" and "any_on" only.

### ISSUE THREAD

**Issue by doomedsardines** [deconz-community/node-red-contrib-deconz#119]
@Zehir welcome on board. I hope you will drive this project forward!

The issue/ improvement idea what I would like to propose is the following:
Currently, "in" node for light group only report two states:
**all_on: true/false
any_on: true/false**
Also, no data is being sent to the "homekit" output.
This makes it impossible to get a group state for lights which are capable of brightness and/or temperature control.
Like e.g. 4 x GU10 Hue lights that I use in one Lamp. 

Current work around that I use is adding 4 individual lights in HomeKit and then group them in the Home app.
Those however proven to be not the most reliable solution. 

Ideally would be great to get real-time brightness and temperature (maybe even color if lamps are capable of it) state of lamps both via "normal" and "homekit" outputs of "in" node. "Out" node seems to be perfectly capable of controlling light groups with all the usual parameters already.

In Phoscon and in HA group's brightness and temperature can be  controlled and is updated:
<img width="1381" alt="Screenshot 2021-02-21 at 11 50 25" src="https://user-images.githubusercontent.com/44230283/108622878-0410c600-743c-11eb-908b-0e5e3646ef07.png">
 So I guess there shall be a possibility to get this in Node-red as well.

**Comment by Zehir** [comment]
Thanks for that, did you have any doc about HomeKit format ? I dod not find anything yes

**Comment by grishmanCH** [comment]
To be honest not so much info or actual documentation.
Output was made to fit the [Homekit-bridged node](https://github.com/NRCHKB/node-red-contrib-homekit-bridged)
There are examples available [here](https://github.com/NRCHKB/node-red-contrib-homekit-bridged/wiki/Example-Bulb-Dimmer) for the lights and some other accessories.
Let me know if you need actual examples.
