### ISSUE TITLE
Homekit for Smart Blinds

### ISSUE THREAD

**Issue by jakubkasparek** [deconz-community/node-red-contrib-deconz#122]
Hello,
can anyone help me to connect IKEA FYRTUR smart blinds to Homekit byt deconz (ConBee II).

Maping on Phoscon look ok, byt connecting v Node-Red is problem for me.
Thanks.
<img width="885" alt="Snímek obrazovky 2021-03-23 v 15 58 12" src="https://user-images.githubusercontent.com/49455498/112167704-f1cba880-8bf0-11eb-8411-3b30627742b2.png">

**Comment by TheNON75** [comment]
Hi @jakubkasparek 
I am not sure it would be a bug.
In fact in many case you might need to fiddle with the codes.
Have you tested the HomeKit node with inject nodes to make sure you get familiar with the expected in payloads and provided out payloads?
Does the deconz in node provide the right format to HomeKit out of the box?
I would guess your issue is more related to generating the right payloads 
You may ask the nrchkb guys as well, they are active on discord too

**Comment by jakubkasparek** [comment]
sorry is not a bug, but for me i only way to asking people which understand payload codes.
Some examples its best for me.

**Comment by Zehir** [comment]
We walk about smart blinds about the state on/off not working.
For homekit nodes you should connect to the second output of the in node labled "homekit" but I am not sure that the input node support blind.
You should come on discord to talk about it : https://discord.gg/NB3xVzZx (this link is valid for 7 days).

**Comment by TheNON75** [comment]
Could this be helpful, @jakubkasparek ?

[HomeKit window cover](https://github.com/NRCHKB/node-red-contrib-homekit-bridged/wiki/Example-Window-Covering)

**Comment by jakubkasparek** [comment]
maybe was something with pairing, because blinder sended brightnes:0

**Comment by Zehir** [comment]
For blind you need to use the [window covering parameters](https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/#window-covering-parameters) in the out node. It's not currently supported by deconz homekit format but you can translate it before sending it to the deconz node with object of type json.
I plan to add this compatibility in 2.0

**Comment by Zehir** [comment]
@jakubkasparek I would like to work on it but I don't have a window cover.
Could you be my beta tester ?

**Comment by Zehir** [comment]
@jakubkasparek I made a first support for the blind, could you test the version [2.0.0-beta.12](https://www.npmjs.com/package/node-red-contrib-deconz/v/2.0.0-beta.12) to see if something works ?

**Comment by Zehir** [comment]
An initial integration will be present in 2.0 but it's need more testing so I moved it to futures versions.

**Comment by jakubkasparek** [comment]
ok i will test it. But im not cure about right pairing IKEA fyrtur to Conbee.

**Comment by Zehir** [comment]
> ok i will test it. But im not cure about right pairing IKEA fyrtur to Conbee.

You can ask for help on the Deconz Community Discord Server [![Discord](https://img.shields.io/badge/discord-online-success)](https://discord.gg/3XGEYY9)
