### ISSUE TITLE
Support for Aqara Wall switch

### ISSUE THREAD

**Issue by KissmanCZ** [deconz-community/node-red-contrib-deconz#123]
Hello everyone, I am trying to get to work Aqara Wall switch (230V). I am able to read state change (1002), but it looks like there is no way how to use "deconz-get" for input? Am I correct or just blind?

**Comment by Zehir** [comment]
You can't do get requests on switch, what values are you trying to get ?
In the next update you will probably be able to do that #120

**Comment by KissmanCZ** [comment]
Sorry, my mistake... I am trying to utilize "deconz-out" to turn on the switch.

**Comment by KissmanCZ** [comment]
@Zehir just a last qestion, it is not possible to use switch in "deconz-out" either so it is part of planned update?

**Comment by Zehir** [comment]
With #120 you will be able to change the name of switch with the out node. You can't do something else on device. What are you looking for ?

**Comment by KissmanCZ** [comment]
I’d like to turn on the switch at least. Checking if it is in on or in off state would ne nice, but not important (useful for HK to se if light is on or off).

**Comment by Zehir** [comment]
With this plugin you can turn on or off the light, you can get the state of the light but not of the switch

**Comment by Zehir** [comment]
> Hello everyone, I am trying to get to work Aqara Wall switch (230V). I am able to read state change (1002), but it looks like there is no way how to use "deconz-get" for input? Am I correct or just blind?

The wired switch are considered as light sometimes and the battery powered are sensors.
Maybe you have a sensor to get the events 1002 and a virtual light to set on/off the switch to turn on the light

**Comment by Zehir** [comment]
Try to check with phoscon if you can find your switch and control it

**Comment by KissmanCZ** [comment]
Switch is visible in Phoscon app, but I cant control it.

**Comment by Zehir** [comment]
Did you see it in the light part ?

**Comment by KissmanCZ** [comment]
No, I can see it under Devices > Switches.

**Comment by Zehir** [comment]
This issue is not related to deconz, I think you switch was not added properly.
Did you add the switch by using phoscon ?

**Comment by KissmanCZ** [comment]
Yes, swith has been added using Phoscon > Devices > Switches > Add new switch. What you mean by not added properly? I can read state changes in NodeRED.

**Comment by Zehir** [comment]
Somebody explain my that you should have 2 things in deconz, one switch to map the button to somethings and one light to control the bulb connected with the 230V wire. Can you toggle on/off the light with your switch ?

**Comment by KissmanCZ** [comment]
Ok, it looks like I found the root cause. I am just updated deconz to the latest version and it finally I can see device as On/Off light. With previous version there was just a switch and nothing more so that is why I was confused...

**Comment by Zehir** [comment]
> Ok, it looks like I found the root cause. I am just updated deconz to the latest version and it finally I can see device as On/Off light. With previous version there was just a switch and nothing more so that is why I was confused...

Always update deconz to lastest version, this could add some devices support
