### ISSUE TITLE
hap.context will be deprecated

### ISSUE THREAD

**Issue by TheNON75** [deconz-community/node-red-contrib-deconz#125]
As in nrchkb "context" from hap will be deprecated soon (in line with hap-nodejs), please verify if it may impact the deconz node.

Currently a workaround ensures that "context" is still sent.

**Comment by Zehir** [comment]
[Related code](https://github.com/deconz-community/node-red-contrib-deconz/blob/a5127c2214f0c754d9856e59f7e86617c5d61bcb/nodes/out.js#L242)
