### ISSUE TITLE
Aqara SP-EUC01 - incomplete ZHAPower state payload

### ISSUE THREAD

**Issue by VaskoJiri** [deconz-community/node-red-contrib-deconz#128]
Hi, I have SP-EUC01 plug. In Node-Red i see only power, no voltage or current values. 

`[{"id":"24961a2b.0b1e46","type":"inject","z":"2dc139cd.1829d6","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":100,"y":1740,"wires":[["e233641e.025898"]]},{"id":"e233641e.025898","type":"deconz-get","z":"2dc139cd.1829d6","name":"","server":"5b99cdef.7c6d14","device":"04:cf:8c:df:3c:89:ed:9d-01-0b04","device_name":"Power 26 : ZHAPower","state":"0","x":240,"y":1660,"wires":[["1802f7dc.e69708"]]},{"id":"1802f7dc.e69708","type":"debug","z":"2dc139cd.1829d6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":500,"y":1660,"wires":[]},{"id":"5b99cdef.7c6d14","type":"deconz-server","name":"Conbee","ip":"192.168.1.30","port":"8090","ws_port":"443","secure":false,"polling":"15"}]
`

<img width="290" alt="Snímek obrazovky 2021-04-12 v 18 32 51" src="https://user-images.githubusercontent.com/81432866/114429293-7fc9fc00-9bbd-11eb-8cf0-1c3cc6be057a.png">

** Hardware / Software **

- raspberry 4   
- version of deconz gateway: [2.10.04 / 14. 3. 2021] 
- version of node-red-contrib-deconz: [1.3.2]

**Comment by Zehir** [comment]
@VaskoJiri can you do a request on the rest api to get the data of your sensor to make sure there is value on the sensor ?
Please read here to see how you can do that : https://dresden-elektronik.github.io/deconz-rest-doc/getting_started/

**Comment by VaskoJiri** [comment]
@Zehir I did it and here is the result. 
`"25": {
        "config": {
            "on": true,
            "reachable": true,
            "temperature": null
        },
        "ep": 1,
        "etag": "6438984bf195bb5d8113db189b2b29d0",
        "lastseen": "2021-04-12T20:06Z",
        "manufacturername": "LUMI",
        "modelid": "lumi.plug.maeu01",
        "name": "Consumption 25",
        "state": {
            "consumption": 359,
            "lastupdated": "2021-04-12T20:06:05.734"
        },
        "swversion": "09-10-2019",
        "type": "ZHAConsumption",
        "uniqueid": "04:cf:8c:df:3c:89:ed:9d-01-0702"
    },
    "26": {
        "config": {
            "on": true,
            "reachable": true,
            "temperature": null
        },
        "ep": 1,
        "etag": "dee8ebd7878775223ea0adda6e46f17b",
        "lastseen": "2021-04-12T20:06Z",
        "manufacturername": "LUMI",
        "modelid": "lumi.plug.maeu01",
        "name": "Power 26",
        "state": {
            "current": null,
            "lastupdated": "2021-04-12T20:06:06.620",
            "power": 49,
            "voltage": null
        },
        "swversion": "09-10-2019",
        "type": "ZHAPower",
        "uniqueid": "04:cf:8c:df:3c:89:ed:9d-01-0b04"
    }`

It's interesting, why it's empty?

**Comment by Zehir** [comment]
I don't know but that mean it's not a node-red related issue.

**Comment by Zehir** [comment]
@Mimiix Can we add the ability to transfer issues on [dresden-elektronik/deconz-rest-plugin](https://github.com/dresden-elektronik/deconz-rest-plugin/issues) ?

**Comment by VaskoJiri** [comment]
@Zehir Thank you. So we’ll transfer the issue to deconz-rest-plugin?

**Comment by Mimiix** [comment]
> @Mimiix Can we add the ability to transfer issues on [dresden-elektronik/deconz-rest-plugin](https://github.com/dresden-elektronik/deconz-rest-plugin/issues) ?
> I checked issues there and did not find anything similar to this.

Nope as it's not in the same organization. Even if we could the bot would close it as it doesn't comply with the template.

**Comment by Zehir** [comment]
I found an issue like this one https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3116

**Comment by Zehir** [comment]
The issue I found is already closed, you should create a new one there.
