### ISSUE TITLE
Lights' "in" node homekit payload color mode is not accurate

### ISSUE THREAD

**Issue by TheNON75** [deconz-community/node-red-contrib-deconz#138]
** Describe issue **
in case of color light capable for both hs and ct, the in node's homekit payload is not considering the current color mode and is sending a complete payload instead of the corresponding data.
For example if ct was sent to a light, the in node is returning hs data as state update

** Your flow here **
Export your flow in json 

** Screens / Logs **

** Hardware / Software **
  - raspberry 3b   
  - version of deconz gateway: 2.11.05 / 5/9/2021
  - version of node-red-contrib-deconz: 1.3.2

**Comment by Zehir** [comment]
@TheNON75 can you test with 2.0 if it's still the case ?

**Comment by TheNON75** [comment]
@Zehir , sorry, still the whole HK payload is sent back by the input node, however the light is correctly reporting the last colormode

**Comment by Zehir** [comment]
Fixed, will be in the next release
