### ISSUE TITLE
Inaccurate conversion of hue to homekit payload

### ISSUE THREAD

**Issue by TheNON75** [deconz-community/node-red-contrib-deconz#139]
** Describe issue **
the in node is sending inaccurate hue data in the homekit payload
Proposed calculation: hue / 182.04167

** Your flow here **
Export your flow in json 

** Screens / Logs **

** Hardware / Software **
  - raspberry 3B   
  - version of deconz gateway: 2.11.05 / 5/9/2021
  - version of node-red-contrib-deconz: 1.3.2

**Comment by TheNON75** [comment]
@Zehir , thanks so much, it is much better, however the returned data should be integer.
This was the payload for testing: `{"Hue":200,"Saturation":100}`

And this is the result:
![image](https://user-images.githubusercontent.com/60628305/141462801-5b33c4c9-f4f5-4999-8ffb-b51a6865db51.png)

**Comment by Zehir** [comment]
> @Zehir , thanks so much, it is much better, however the returned data should be integer. This was the payload for testing: `{"Hue":200,"Saturation":100}`
> 
> And this is the result: ![image](https://user-images.githubusercontent.com/60628305/141462801-5b33c4c9-f4f5-4999-8ffb-b51a6865db51.png)

Are you sure that should be an integer ?

![image](https://user-images.githubusercontent.com/845225/142063704-5435b1f0-2568-48be-9730-98537f6755d6.png)

**Comment by TheNON75** [comment]
Indeed there is float mentioned, however the step value is 1

**Comment by TheNON75** [comment]
@Zehir 
So the format is float, the unit is percentage, step is 1

It seems like Float is not resulting in an error, but it is rounded automatically

**Comment by Zehir** [comment]
FiIxed in lastest release
