### ISSUE TITLE
old embedded jQuery module "multiple-select" v1.4.2 breaks monaco-editor in node-red 2.0.0

### ISSUE THREAD

**Issue by Steve-Mcl** [deconz-community/node-red-contrib-deconz#140]
** Describe issue **
Hi, much like the [issue I raised on node-red-contrib-zigbee2mqtt](https://github.com/andreypopov/node-red-contrib-zigbee2mqtt/issues/41), this repo also has an old version of "multiple-select" embedded in the `static/` folder that breaks the new monaco editor

The issue is (i believe) specific to V1.4.2 - see this issue: wenzhixin/multiple-select#483

Could you please update to V1.5.2 as it does not cause the editor to break.

** Screens / Logs **
![image](https://user-images.githubusercontent.com/44235289/121816618-94397c00-cc74-11eb-8c0c-29ec35b50697.png)

**Comment by Zehir** [comment]
Hi, I already update it on the #120 branch but it's will take a while to came out. I may push a Quick fix

**Comment by Steve-Mcl** [comment]
Ah, sorry, I hadnt seen that.

No rush apart from node-red 2.0.0 is due to land fairly soon.

Perhaps you can just update that jQuery lib? (assuming it doesnt break anything)

Thank you.

**Comment by Steve-Mcl** [comment]
Hi, is https://www.npmjs.com/package/node-red-contrib-deconz-test-zehir also your package? that too has the same issue. (the npm link actually points to this repo)

**Comment by Zehir** [comment]
> Hi, is https://www.npmjs.com/package/node-red-contrib-deconz-test-zehir also your package? that too has the same issue. (the npm link actually points to this repo)

Yes it is, I cant remember why I publish it

**Comment by Steve-Mcl** [comment]
> Yes it is, I cant remember why I publish it

Thanks for confirming.

PS, I can also confirm, updating the `.js` and `.css` files of "multiple-select" lib to V1.5.2 does fix this issue for your node.

NOTE however, as I do not use this node I cannot confirm if the component works as it should or not - just that it no longer breaks monaco editor.


Cheers, Steve.

**Comment by Zehir** [comment]
Fixed in 1.3.3
