### ISSUE TITLE
Out-Node does not recognise scenes from a Philips Hue lamp

### ISSUE THREAD

**Issue by haegar33** [deconz-community/node-red-contrib-deconz#141]
** Describe issue **
2 test scenes have been defined in the Phoscon App for my new Philips Go Hue Lamp. Within Phoscon I can start/stop these scenes with no problem. However using the DeConZ NodeRed Node to access the scenes the list is empty. A "refresh device list" command has no effect. Restart of NodeRed has no effect. 

** Your flow here **
[{"id":"7bf260d9.d30508","type":"deconz-output","z":"86f88977.a03d4","g":"8f0feefb.f0f5","name":"","server":"ba1aea25.be28c8","device":"00:17:88:01:09:8a:b3:9f-0b","device_name":"Philips Hue : Extended color light","command":"scene","commandType":"deconz_cmd","payload":"payload","payloadType":"msg","transitionTime":"","transitionTimeType":"num","x":870,"y":1760,"wires":[]},{"id":"ba1aea25.be28c8","type":"deconz-server","name":"DeCONZ Pi3","ip":"192.168.178.45","port":"8080","apikey":"AF090163BF","ws_port":"443","secure":false,"polling":"15"}]

** Screens / Logs **
<img width="495" alt="Screenshot NodeRed" src="https://user-images.githubusercontent.com/22793462/123538560-d1524380-d735-11eb-9ce3-2c6be7c5af09.png">

** Hardware / Software **
  - raspberry 3B  

version of deconz gateway: 2.11.05 / 5/9/2021
  - version of node-red-contrib-deconz: 1.3.2

**Comment by haegar33** [comment]
Could not find a simple delete button for an issue....??
Issue resolved, scenes can only be access by light groups, not individual lights. Choosing a light group in the node reveals the list of scenes

**Comment by Zehir** [comment]
> Could not find a simple delete button for an issue....??
> Issue resolved, scenes can only be access by light groups, not individual lights. Choosing a light group in the node reveals the list of scenes
> 

Yes the scenes are on the lights group.
No you cant delete an issue, just close it
