### ISSUE TITLE
deconz-get throws exception when "not reachable" 

### ISSUE THREAD

**Issue by ostauss** [deconz-community/node-red-contrib-deconz#142]
I need to start a control flow when a deCONZ device is "not reachable". 
Currently, I don't have an idea how to implement this.

**Comment by ostauss** [comment]
Alternative solution. When deconz-get receives a trigger with "not reachable" device a message is available on "out". 
Kind of payload.state="not reachable"

**Comment by TheNON75** [comment]
Hi @ostauss,

place a debug node in your flow after the deconz node and set it to complete msg
Now you should see where to look for 
`“reachable”:true/false`

is that what you are looking for?

**Comment by Zehir** [comment]
It's will be easier on the next version to get things like this #120
