### ISSUE TITLE
node Red still show version 1.3.2 which is not working with Node Red 2

### ISSUE THREAD

**Issue by syswombat** [deconz-community/node-red-contrib-deconz#143]
Hello
there is no update to 1.3.3 showing 
https://flows.nodered.org/node/node-red-contrib-deconz

wich would be important to use Node Red 2.x

have a nice day
vinc

**Comment by Steve-Mcl** [comment]
Hi maintainers, the node-red flows site no longer scans npm. You need to log into flows site and re-add your node. 

I will request a refresh on your behalf to get it updated on the flows site so users can benefit from the update.

**Comment by Mimiix** [comment]
@Zehir do I need to do something?

**Comment by Zehir** [comment]
> @Zehir do I need to do something? 

No it's ok.

Inforgot to update the plugin info on the nodered website. Anybody can do it. Thanks @Steve-Mcl
