### ISSUE TITLE
Cannot uninstall deCONZ

### ISSUE THREAD

**Issue by svisso** [deconz-community/node-red-contrib-deconz#145]
Dear community
It somehow happened that I found myself confronted to the message "Unknown node type Deconz-Server". Before, I had fiddeled around with the "IKEA Symfonisk & Gauges using Deconz-Zigbee" module, without success while trying to bend the flow from Deconz over to Zigbee2MQTT which I use here on HomeAssistant.

In order to get rid of the error, I installed this Node-Red-Contrib-Deconz module. Now, the error has gone.
But as I try to uninstall the module in order to do a rollback, I am unable to uninstall. There are six nodes plus the Deconz-Server node reported to be active. When I deactivate the 6 nodes, the server node remains flagged active, even after restarting Node Red.
![image](https://user-images.githubusercontent.com/77211341/127747228-141ac970-9bab-4987-9b3b-2d35b8f035e4.png)

I am afraid I have to force remove Node-Red-Contrib-Deconz. Would someone be so kind as to advice me, please?

Thank you in advance.
Michael

**Comment by Zehir** [comment]
If you wan't to not use this plugin inside node red you can safely remove it. This will not hurt your HA or Deconz installation. You can see the configuration node of type deconz-server if you want to delete it before uninstall the plugin

**Comment by svisso** [comment]
Thank you Zehir, I found the mentioned config node and deleted it. Clear now.
