### ISSUE TITLE
WebSocket disconnected: 1000

### ISSUE THREAD

**Issue by RitaSghe** [deconz-community/node-red-contrib-deconz#146]
** Describe issue **
After last update at Deploy I have this error:   **WebSocket disconnected: 1000**
but all works fine .....

** Your flow here **
Export your flow in json 

** Screens / Logs **

** Hardware / Software **
  - raspberry 4   
  - version of deconz gateway: [2.11.05 / 9/5/2021] 
  - version of node-red-contrib-deconz: [1.3.3]

**Comment by Zehir** [comment]
What version of node-red are you using ?
Did you use home assistant ?

**Comment by RitaSghe** [comment]
1) Node red 1.3.4

2) NO

**Comment by Zehir** [comment]
Is node red ans deconz on the same host?
What kind of ip did you set inside the configuration node ?

**Comment by Zehir** [comment]
Can you send a screen show of the error ?

**Comment by RitaSghe** [comment]
Yes, the same host ....

![img01](https://user-images.githubusercontent.com/81916825/128704106-be7f1e71-2676-4636-9a5b-576c03c96d0e.png)

![img02](https://user-images.githubusercontent.com/81916825/128704122-8517e972-253c-4240-8083-165459a4942a.png)

**Comment by Zehir** [comment]
Can you browse this link from your local network and make sure that the port is correct ?
https://phoscon.de/discover
And then using the rest api to check the websocket port ?
Also can you try with 127.0.0.1 as ip address ?

**Comment by Zehir** [comment]
any news @RitaSghe ?

**Comment by RitaSghe** [comment]
Yes, the port is correct ...

**Comment by Zehir** [comment]
and with 127.0.0.1 or localhost ?

**Comment by Shad0wWulf** [comment]
Just to confirm I have the same issue, NR: 1.2.9

Running on a Pi

![image](https://user-images.githubusercontent.com/5139511/132074095-6a44d245-4139-4f2e-bd9c-3b604a319667.png)

Node Red Info

![Screenshot 2021-09-04 002539](https://user-images.githubusercontent.com/5139511/132073948-9dccf24c-a265-4bcf-a0e7-ad2189b4923b.png)

Discover Info
![Screenshot 2021-09-04 002453](https://user-images.githubusercontent.com/5139511/132073950-1508256f-d7e9-4025-a994-341f4ef046d4.png)

ConBee Version

![image](https://user-images.githubusercontent.com/5139511/132074005-4d376f87-4c6f-4ace-b55b-7a8b6b39e4de.png)

**Comment by SmartPhysikant** [comment]
Hi, same here. Any solution yet?

**Comment by Zehir** [comment]
Before the error 1000 was just muted inside the node. It's seems there is a lot of disconnections  with the websocket but he reconnect to it fast so I dont think it's à big issue.
I think we cant do anything for that

**Comment by Zehir** [comment]
In 2.0 we don't display websocket errors 1000 but they still occur like before
