### ISSUE TITLE
Can't control window covering

### ISSUE THREAD

**Issue by raddi** [deconz-community/node-red-contrib-deconz#161]
So with version 2.x i can no longer control my windows covering anymore. it does not matter which settings i use, set it to x percent "Lift" or "Open/Close" set to open or close, nothing happens. I can still control it with the deconz homebridge plugin so there is a problem with this node-red plugin.

**Comment by Zehir** [comment]
The 2.0.7 fixed this issue, could you try and give me feedback ?

**Comment by raddi** [comment]
Yes, working as expected now, thank you for the fast support!
