### ISSUE TITLE
deconz not recheable

### ISSUE THREAD

**Issue by matteos1** [deconz-community/node-red-contrib-deconz#162]
### Current Behavior

after updating to the latest version, the deconz node connects for a while and then goes to deconz not recheable.
is there a solution to this problem?
the system running on hassio -

### Example flow

```json
paste your flow here
```

### Environment

- deCONZ plugin version:
- HomeKit plugin version (if used):
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by branitelj91** [comment]
Same here. 

After update, node red cannot access deconz
It was all ok before update

**Comment by Zehir** [comment]
> > What version are you using ? There is any error on the node red logs?
> 
> version is 2.0.6, (assuming latest)
> Node-red logs are giving errors: 
> 
> > 14 Oct 19:09:53 - [error] [deconz-server:Phoscon-GW] discoverDevices: Can't connect to deconz API since starting. Please check server configuration.
> 
> 

Can you try reconfigure your server node with the auto fetch settings ?

**Comment by matteos1** [comment]
i configure with auto settings but there is always same problem..
node red on hassio is not 2.0...

**Comment by Zehir** [comment]
> i configure with auto settings but there is always same problem..
> node red on hassio is not 2.0...

You can update from the supervisor to have node red 2.x

**Comment by Zehir** [comment]
> version 10.0.1

This is the version of the node-red addon so your are using the version of node-red 2.0.6.

![image](https://user-images.githubusercontent.com/845225/137593612-b18cc46e-9d60-46fb-adf6-037ed4183058.png)

Can you send me a screenshot of the deconz-server configuration ?

**Comment by Zehir** [comment]
@branitelj91 Can you send me a screenshot of your deconz-server settings ?

**Comment by Zehir** [comment]
@branitelj91 We might found the issue, can you do a request using a web browser to this url and send me back the result ?
```
http://{{ip}}:{{port}}/api/{{API Key}}/groups/0
```

**Comment by Zehir** [comment]
The 2.0.7 fixed this issue, could you try and give me feedback ?

**Comment by branitelj91** [comment]
> The 2.0.7 fixed this issue, could you try and give me feedback ?

it is working now. 

Thank You for the hard work. 
I owe You a pint  :D

**Comment by Zehir** [comment]
> > The 2.0.7 fixed this issue, could you try and give me feedback ?
> 
> it is working now. 
> 
> Thank You for the hard work. 
> I owe You a pint  :D 
> 
> 
> 

Haha thanks ;)
