### ISSUE TITLE
Unable to upgrade to 2.0.7 (Server restore nessesary after upgrade)

### ISSUE THREAD

**Issue by guny74** [deconz-community/node-red-contrib-deconz#164]
### Current Behavior

I tried to upgrade from 1.3.4 to 2.0.7 several times. 
Every time after upgrade & restart the Node Red UI (redmatic based on node red) stops on loading nodes and flows.

I tried to edit the deconz config node directly  after update the package, than deploy & restart (before reboot). -> Error (& Restore Server)
I tried to edit deconz config node + every deconz node. deploy and restart server --> -> Error (& Restore Server)

In the log I found after node red restart the following error 

` [deconz-server:DeconsDocker] Deconz Server node error TypeError: this.config.device.substr is not a function
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red: Error from server node #1 TypeError: this.config.device.substr is not a function
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red:     at ConfigMigrationHandlerOutput.migrateFromLegacy (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/src/migration/ConfigMigrationHandlerOutput.js:49:40)
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red:     at ConfigMigrationHandlerOutput.migrate (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/src/migration/ConfigMigrationHandlerOutput.js:11:53)
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red:     at ConfigMigration.migrate (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/src/migration/ConfigMigration.js:37:26)
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red:     at ConfigMigration.applyMigration (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/src/migration/ConfigMigration.js:55:27)
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red:     at ServerNode.migrateNodeConfiguration (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/nodes/server.js:764:51)
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red:     at ServerNode.initNode (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/nodes/out.js:78:33)
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red:     at ServerNode.emit (events.js:327:22)
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red:     at ServerNode.Node.emit (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:181:20)
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red:     at pooling (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/nodes/server.js:77:34)
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Oct 21 19:30:46 CCU3RPI4 daemon.err node-red:     at async /usr/local/addons/redmatic/var/node_modules/node-red-contrib-deconz/nodes/server.js:114:17`

Any Idea how to solve this 

Thanks

### Example flow

```json
paste your flow here
```

### Environment

- deCONZ plugin version: 2.0.7
- HomeKit plugin version (if used):  no
- Node-RED version: 1.2.9
- Node.js version: 14.16.0
- - Platform/OS: Raspberry pi (OS of Raspberrymatic)

**Comment by guny74** [comment]
Sorry. missed you answer.  Do I have to open only teh config node or all input/output nodes ?

**Comment by Zehir** [comment]
> Sorry. missed you answer. Do I have to open only teh config node or all input/output nodes ?

It's better to open all nodes and server nodes to update the configuration and make sure the migration worked fine

**Comment by guny74** [comment]
Thank you. Version 2.0.8 solved my problem.
