### ISSUE TITLE
Plugin sends again the last state of button when deployed

### ISSUE THREAD

**Issue by gsieben** [deconz-community/node-red-contrib-deconz#187]
### Current Behavior

I have installed Node Red 2.1,3. In addition node-red-contrib-deconz in version 2.1.3.

An already fixed problem has appeared again. 

When deploying changes in Node Red, the last button signal is sent again.

See also: https://github.com/deconz-community/node-red-contrib-deconz/issues/85 

### Expected Behavior

No button signal should be sent during deploy. 

### Steps To Reproduce

Would not see anything special here. If it is not reproducible, I will be happy to provide more information. 

### Environment

- deCONZ plugin version:2.13.02 / 9.12.2021
- HomeKit plugin version (if used): not used
- Node-RED version: 2.3.1
- Platform/OS: Raspbian Linux 10

**Comment by Zehir** [comment]
Could you provide a sample flow ?

**Comment by Zehir** [comment]
@gsieben any updates ?

**Comment by Zehir** [comment]
No response from user
