### ISSUE TITLE
"WebSocket disconnected: 1000"

### ISSUE THREAD

**Issue by ismoo1** [deconz-community/node-red-contrib-deconz#192]
### Current Behavior

In my earlier setup I did not have this notice "WebSocket disconnected: 1000", but now after my setup got corrupted I recreated everything from scratch in similar way as earlier (PI, Deconz, node-red etc SW), only difference was that I updated Conbee firmare into latest Dec version, (though my stick was rather new obtained in October), and right in 1st integration to test I get this notice, even I can switch 1st test lamp on/off successfully, so looks to be cosmetic as switching fine, perhaps related to latest firmware?

### Example flow

```json
paste your flow here
```

### Environment

- deCONZ plugin version:
- HomeKit plugin version (if used):
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Zehir** [comment]
The websocket 1000 error happen sometime but the error is not yet cleared correctly. For now, you can ignore it if everything is working fine.
Also, when you deploy you get this error but it's ok. This happen when the nodes are stopped, the websocket is disconnected, the error should not be displayed. #165
