### ISSUE TITLE
No ouput with In-Nodes

### ISSUE THREAD

**Issue by Draugr793** [deconz-community/node-red-contrib-deconz#200]
### Current Behavior

I'm using a In-Node for a Switch. The In-Node has a very simple Output configuration only for the button event. 
When i push the button no output is triggered.

When i open the node after pushing the switch i can see the changed buttonevent values in the dropdown of the output configuration. It seems that the changed button events will "reach" the Node, but are note routed to the output.

I have the same behavior to all other In-Nodes (Lights, Temperature Sensors etc.).

Another abnormality is that the small label under the nodes always shows "connected" and not the output value (buttonevent) etc.

It seems that there is no problem with Out-Nodes. Controlling lights for example works very fine.

### Expected Behavior

After pushing a button for example i will except that the button event will be tranferd to the output of the In-Node.

### Steps To Reproduce

- Create a simple In-Node for a switch (or something similar)
- Simple Output configuration for buttonevent-State with 'Output Always' selected
- Add debug node to output
- Deploy everything and test it with pushing button

### Example flow

```json
[
   {
      "id":"62954ab076c68b75",
      "type":"debug",
      "z":"7c4a12fa.e3a17c",
      "name":"",
      "active":true,
      "tosidebar":true,
      "console":false,
      "tostatus":false,
      "complete":"false",
      "statusVal":"",
      "statusType":"auto",
      "x":440,
      "y":640,
      "wires":[
         
      ]
   },
   {
      "id":"a26d08acd7634314",
      "type":"deconz-input",
      "z":"7c4a12fa.e3a17c",
      "name":"Gangway Switch Desk",
      "topic":"",
      "config_version":2,
      "server":"67d4353b.84166c",
      "statustext":"",
      "statustext_type":"default",
      "search_type":"device",
      "device_list":[
         "sensors/uniqueid/04:cf:8c:df:3c:79:0f:f5-01-0012"
      ],
      "device_name":"",
      "query":"{}",
      "outputs":1,
      "output_rules":[
         {
            "type":"state",
            "format":"single",
            "output":"always",
            "onstart":true,
            "payload":[
               "buttonevent"
            ]
         }
      ],
      "x":200,
      "y":640,
      "wires":[
         [
            "62954ab076c68b75"
         ]
      ]
   },
   {
      "id":"67d4353b.84166c",
      "type":"deconz-server",
      "name":"Phoscon-GW",
      "config_version":1,
      "ip":"192.168.1.122",
      "port":"8090",
      "ws_port":"443",
      "secure":false,
      "polling":"15"
   }
]
```

### Environment

- deCONZ plugin version: 2.3.3
- HomeKit plugin version (if used): -
- Node-RED version: 2.1.4
- Node.js version: 14.18.2
- npm version: 6.14.15
- Platform/OS: Windows 10
- Browser: Chrome v97.0.4692.99

**Comment by Zehir** [comment]
@Draugr793 I tried your flow in my network and it's working fine for me. Maybe you have an issue with the websocket.
Could you try to wire a deconz event node to a debug node to see if you get your switchs events ?

**Comment by shin10** [comment]
I ran in a similar or the same issue and found a lot of other issues regarding to the websocket connection. Every 15 seconds node-red's debug view showed
```
Error
"WebSocket error: Error: connect ECONNREFUSED 127.0.0.1:8081"

Wraning
"WebSocket disconnected: 1006 - "
```
I guess that's caused by the polling.
That leads to funny things like a light state toggling output node will only toggle the light once until the polling refreshes the new state.  

My guess is that this problem is comming up every once in a while here because the `magick` button suggests a wrong websocket port. In my case `8081` instead of `443`. Fixing the port number resolved all my issues.

**Comment by Zehir** [comment]
Did you use the auto discovery button ?

**Comment by Draugr793** [comment]
@Zehir I tried with a deconz-event node and a debug node. Same behavior: No Output in Debug
Little label underneath the deconz-event-node shows "0 events".

**Comment by Zehir** [comment]
Yes you have an issue woth the websocket port. The port is not alway the same, you can do an api request to /config to get it

**Comment by Draugr793** [comment]
Very strange behavior, because the /config request displays the correct set port.
However, currently i am switchen from raspberry pi to intel nuc with docker. Last weekend i migrate Node-RED and deconz. And from now everything works fine. So i close the issue.

Thank you very much for your help and of course for your work!
