### ISSUE TITLE
deconz not recheable

### ISSUE THREAD

**Issue by Hassefar** [deconz-community/node-red-contrib-deconz#203]
### Current Behavior

Deconz connects fine but after some time, I get the "deconz not recheable" under several of my nodes. If I re-deploy the flow, the nodes will connect again. Basically the same issues as: https://github.com/deconz-community/node-red-contrib-deconz/issues/162

However, this is not resolved for me. :-(

I am currenlty of the newest version of NR and 2.3.3 of node-red-contrib-deconz

### Example flow

```json
paste your flow here
```

### Environment

- deCONZ plugin version: 2.3.3
- Node-RED version: 2.2.0
- Node.js version:
- npm version:
- Platform/OS: Rasbian
- Browser:

**Comment by Zehir** [comment]
I think theses errors are just not properly cleared. There is no to worry about but I will look in to it when I have time

**Comment by svenschuldt** [comment]
Same for me - when you say not properly cleaned, what do you mean? 
On my side, the node does not work and consequently none of the flows the node is connected to.
Thanks for helping!

**Comment by shlagwuk** [comment]
Same problem here. Did you find a solution?

**Comment by Hassefar** [comment]
I chabged the Deconz server reference in the nodes to a specific IP which have helped alot. The problem is still there but only very rare.

**Comment by shlagwuk** [comment]
It's a leat once everyday for me. Anything I can do to investigate this error?

**Comment by Zehir** [comment]
> It's at least once everyday for me. Anything I can do to investigate this error? 

You can check the node red logs for errors. Also try to connect to the websocket if there is any connexion lost

**Comment by shlagwuk** [comment]
in the docker node red log, I get this error:
`19 Jul 06:06:46 - [warn] [deconz-server:Phoscon-GW] WebSocket connection timeout, reconnecting
19 Jul 06:06:46 - [warn] [deconz-server:Phoscon-GW] WebSocket disconnected: 1006 -
19 Jul 06:06:56 - [info] [deconz-server:Phoscon-GW] WebSocket opened
`

**Comment by Zehir** [comment]
> in the docker node red log, I get this error:
> `19 Jul 06:06:46 - [warn] [deconz-server:Phoscon-GW] WebSocket connection timeout, reconnecting`
> `19 Jul 06:06:46 - [warn] [deconz-server:Phoscon-GW] WebSocket disconnected: 1006 -`
> `19 Jul 06:06:56 - [info] [deconz-server:Phoscon-GW] WebSocket opened`
> 

Yep that is an unexpected deconnection. You can't really do something about it...

**Comment by Zehir** [comment]
In earlier version of the plugin theses errors wat not showed to the user

**Comment by Zehir** [comment]
@Hassefar @shlagwuk @Alex-joomla @svenschuldt do you still get theses errors ?

**Comment by Alex-joomla** [comment]
Hi @Zehir, good start for 2023 :-)


Just checked and I still get the same messages 
<img width="292" alt="Bildschirmfoto 2022-12-31 um 11 50 09" src="https://user-images.githubusercontent.com/32268233/210233335-9218832a-bcf8-4df5-892b-b6fc03f044de.png">

**Comment by Zehir** [comment]
Could you try again with latest version of node red and the plugin ?
