### ISSUE TITLE
Battery Homekit status issue

### ISSUE THREAD

**Issue by Nazarbayevv** [deconz-community/node-red-contrib-deconz#212]
### Current Behavior

node-red-contrib-deconz v2.3.3

![image](https://user-images.githubusercontent.com/50654913/181996998-889a6c59-7fe2-4263-ad12-2bc486970b26.png)

![image](https://user-images.githubusercontent.com/50654913/181997028-89ffe459-e7c9-4e9f-aa75-e6b6edcdf4c4.png)

I don't see battery value from homekit outputs. From output config type I can see battery status and outher values:

{"battery":100,"offset":0,"on":true,"reachable":true}

### Example flow

```json
paste your flow here
```
[{"id":"7d83f01ae41e232f","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"3c475a812a54efbf","type":"debug","z":"7d83f01ae41e232f","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1070,"y":260,"wires":[]},{"id":"a08478a1562797de","type":"deconz-battery","z":"7d83f01ae41e232f","name":"","topic":"","config_version":2,"server":"da76db0b.163948","statustext":"","statustext_type":"auto","search_type":"device","device_list":["sensors/uniqueid/00:15:8d:00:07:d3:a5:0a-01-0402"],"device_name":"","query":"{}","outputs":2,"output_rules":[{"type":"config","format":"single","onstart":true,"uniqueId":"ui-id-51"},{"type":"homekit","format":"single","onstart":true,"uniqueId":"ui-id-52"}],"x":860,"y":280,"wires":[["3c475a812a54efbf"],["b8ccf42b955f5ac1"]]},{"id":"b8ccf42b955f5ac1","type":"debug","z":"7d83f01ae41e232f","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1070,"y":300,"wires":[]},{"id":"da76db0b.163948","type":"deconz-server","name":"Deconz","config_version":1,"ip":"192.168.88.9","port":"80","ws_port":"443","secure":false,"polling":"15"}]

### Environment

- deCONZ plugin version: 2.3.3
- HomeKit plugin version (if used): 1.4.3
- Node-RED version: 2.1.4
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Zehir** [comment]
The automatic payload for HomeKit don't include battery by default, did you see the `BatteryLevel` option in the select ?

**Comment by Zehir** [comment]
Is is ok for you @Nazarbayevv  ?

**Comment by Nazarbayevv** [comment]
Hello, for chack battery lavel I use this one:
![image](https://user-images.githubusercontent.com/50654913/183246760-9f002fac-8ee1-4829-a997-6f6979e6d2c2.png)

And all my nodes, befor global migration to new deconz version, show battery status for HomeKit correctly?

Where should I find  BatteryLevel option?

**Comment by Zehir** [comment]
You can find it in the output configuration
![image](https://user-images.githubusercontent.com/845225/183252032-0f951d7d-8f02-4e9c-8114-0be9a2f4cea2.png)

**Comment by Nazarbayevv** [comment]
Yes, I received BetteryLevel from "in" node. 
Previously, I used bettery node for this. What is role of Battery node nowadays?

**Comment by Zehir** [comment]
None, battery node is keept for legacy reason. It's may be deprecated soon

**Comment by Nazarbayevv** [comment]
Ok. I close issue.

Thanks for support
