### ISSUE TITLE
"OUT" Node for TRV's (Thermostatic radiator valves)

### ISSUE THREAD

**Issue by AarneAarebye** [deconz-community/node-red-contrib-deconz#218]
### My idea

Hi all, TRV's are not natively usable as e.g. lights or window covers. So I used the HomeKit Type to send parameters to the TRV via the "out" node. I tried to send:
{"CurrentTemperature":21.2,"TargetTemperature":25.4,"TargetHeatingCoolingState":1,"TemperatureDisplayUnits":0,"LockPhysicalControls":0,"HeatingThresholdTemperature":25,"WindowOpenState":0}
to control the TRV...
In the result output, all the input parameters landed in the "_in" because of "All input values that make conflict with the output are suffixed by _in."
So, my question is: Is there a way to control a TRV? If so, how?

**Comment by AarneAarebye** [comment]
rtfm

**Comment by Zehir** [comment]
Yes everything that conflict is moved to avoid data loss. I know the documentation need improvements with more examples. Fell free to join the discord if you have a quick question about something
