### ISSUE TITLE
FR: Pull link quality for nodes

### ISSUE THREAD

**Issue by Jacksonbm1** [deconz-community/node-red-contrib-deconz#223]
### My idea

As far as I can tell, you cannot pull in link quality with the current node-red integration. It would be extremely helpful if you could. I don't know if this is possible, but you would probably have it be an object with multiple dimensions (one for every node it is connected to with a subdimension of ingoing and outgoing traffic). I assume this is possible since deconz has the data and we're pulling from deconz correct?

Lmk if I can help debug anything.

Best,

**Comment by Zehir** [comment]
Hello,

Are you trying to get the green wire data you see in the GUI ?
As far I know this data id not exposed in the rest api.

**Comment by Jacksonbm1** [comment]
You're right. I was getting the command line plugin mixed up with the rest API. Shame it's not possible. I'm going to leave this open and link it to this blocking bug: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4605

**Comment by Zehir** [comment]
What command line plugin ?

**Comment by Jacksonbm1** [comment]
This one: https://github.com/ma-ca/deconz-cli-plugin/blob/master/README.md It seems like you can pull in link quality through this, though I'm not positive.

**Comment by Zehir** [comment]
This plugin is 5 years old, does he still works ?

**Comment by Jacksonbm1** [comment]
No clue. I feel like on the one hand deconz has new devices getting support all the time. On the other, it feels like a TON of the documentation is super super outdated. [This page](https://dresden-elektronik.github.io/deconz-rest-doc/devices/) for example (though now that I look it actually seems to finally have. been updated a bit). I am planning on trying to use the plug in and see if it works.

**Comment by Zehir** [comment]
Yes the device support list is outaded, it's suport many devices now. Since the DDF stuff came out.

You can use the api node to query anything on the rest api. There is also some undocumented api endpoint in "beta" and that why there are kot documented. You can check the rest api plugin code to see them
