### ISSUE TITLE
Transition time for led not zero

### ISSUE THREAD

**Issue by VincentLiq** [deconz-community/node-red-contrib-deconz#224]
I have a led strip controller from Gledopto. We have an issue when we change the light color, the light changes the color with a transition time. but we have the node configured to have a transition Time of zero. The example below will change the color from blue to red. 
(https://github.com/deconz-community/node-red-contrib-deconz/assets/124067481/00399b71-69b5-4101-86e2-c3b11d749475)

`[
    {
        "id": "13fd5aaabdcf3003",
        "type": "deconz-output",
        "z": "c80bd961ee1ee964",
        "name": "ledstrip",
        "config_version": 2,
        "server": "",
        "statustext": "",
        "statustext_type": "default",
        "search_type": "device",
        "device_list": [
            "lights/uniqueid/00:12:4b:00:1f:6a:0d:7c-0b"
        ],
        "device_name": "",
        "query": "{}",
        "commands": [
            {
                "arg": {
                    "on": {
                        "type": "keep",
                        "value": ""
                    },
                    "alert": {
                        "type": "str",
                        "value": ""
                    },
                    "effect": {
                        "type": "str",
                        "value": "none"
                    },
                    "colorloopspeed": {
                        "type": "num",
                        "value": "0"
                    },
                    "transitiontime": {
                        "type": "num",
                        "value": "0"
                    },
                    "retryonerror": {
                        "type": "num",
                        "value": "0"
                    },
                    "aftererror": {
                        "type": "continue",
                        "value": ""
                    },
                    "bri": {
                        "direction": "set",
                        "type": "num",
                        "value": "255"
                    },
                    "sat": {
                        "direction": "set",
                        "type": "num",
                        "value": "255"
                    },
                    "hue": {
                        "direction": "set",
                        "type": "msg",
                        "value": "hue"
                    },
                    "ct": {
                        "direction": "set",
                        "type": "num",
                        "value": ""
                    },
                    "xy": {
                        "direction": "set",
                        "type": "json",
                        "value": "[]"
                    }
                },
                "type": "deconz_state",
                "domain": "lights"
            }
        ],
        "specific": {
            "delay": {
                "type": "num",
                "value": "50"
            },
            "result": {
                "type": "at_end",
                "value": ""
            }
        },
        "x": 870,
        "y": 380,
        "wires": [
            [
                "91b59e9b6914e976"
            ]
        ]
    }
]`

**Comment by Zehir** [comment]
It's look like there is a unrelated error about colorloop. Can you show the node configuration ?

About the transition time It's send, maybe It's not supported by the device

**Comment by VincentLiq** [comment]
this is the configuration of the phoscon node
`[
    {
        "id": "ea372b9a4ee1ad92",
        "type": "deconz-output",
        "z": "73e6b4e7cc900d54",
        "name": "ledstrip",
        "config_version": 2,
        "server": "e401b4cf41d8583d",
        "statustext": "",
        "statustext_type": "default",
        "search_type": "device",
        "device_list": [
            "lights/uniqueid/00:12:4b:00:1f:6a:0d:7c-0b"
        ],
        "device_name": "",
        "query": "{}",
        "commands": [
            {
                "arg": {
                    "on": {
                        "type": "keep",
                        "value": ""
                    },
                    "alert": {
                        "type": "str",
                        "value": ""
                    },
                    "effect": {
                        "type": "str",
                        "value": "none"
                    },
                    "colorloopspeed": {
                        "type": "num",
                        "value": "0"
                    },
                    "transitiontime": {
                        "type": "num",
                        "value": "0"
                    },
                    "retryonerror": {
                        "type": "num",
                        "value": "0"
                    },
                    "aftererror": {
                        "type": "continue",
                        "value": ""
                    },
                    "bri": {
                        "direction": "set",
                        "type": "num",
                        "value": "255"
                    },
                    "sat": {
                        "direction": "set",
                        "type": "num",
                        "value": "255"
                    },
                    "hue": {
                        "direction": "set",
                        "type": "msg",
                        "value": "hue"
                    },
                    "ct": {
                        "direction": "set",
                        "type": "num",
                        "value": ""
                    },
                    "xy": {
                        "direction": "set",
                        "type": "json",
                        "value": "[]"
                    }
                },
                "type": "deconz_state",
                "domain": "lights",
                "uniqueId": "ui-id-12"
            }
        ],
        "specific": {
            "delay": {
                "type": "num",
                "value": "50"
            },
            "result": {
                "type": "at_end",
                "value": ""
            }
        },
        "x": 660,
        "y": 320,
        "wires": [
            []
        ]
    },
    {
        "id": "e401b4cf41d8583d",
        "type": "deconz-server",
        "name": "DTEC: 1C",
        "config_version": 1,
        "ip": "172.16.0.172",
        "port": "80",
        "ws_port": "8088",
        "secure": false,
        "polling": "15"
    }
]`

**Comment by Zehir** [comment]
@VincentLiq is this issue still present ?
