### ISSUE TITLE
deCONZ error WebSocket disconnected: 1006 -

### ISSUE THREAD

**Issue by Mikee1234K** [deconz-community/node-red-contrib-deconz#225]
### Current Behavior

I had to re-authorize my deconz nodes, which seemed to worked ok initially. The node says connected, but a second later I get a red dot under it with 1006. In the debug window it shows

"WebSocket disconnected: 1006 - 
In the Node Red cmd window I see this:

16 Jun 11:06:36 - [error] [deconz-server:Phoscon-GW] WebSocket error: Error: connect ECONNREFUSED 192.168.x.x:8080
16 Jun 11:06:36 - [warn] [deconz-server:Phoscon-GW] WebSocket disconnected: 1006 -

### Example flow

```json
paste your flow here
```

### Environment

- deCONZ plugin version: 2.3.9
- HomeKit plugin version (if used):
- Node-RED version: 3
- Node.js version: 18.16.0
- npm version: 9.5.1
- Platform/OS: Win 11
- Browser:

**Comment by Zehir** [comment]
Can you check if the websocket port is valid ? Try pressing the zuto configure magick button

**Comment by Mikee1234K** [comment]
I pressed the auto config, did not see any errors. It pulls in all the devices so I assumed it was ok

**Comment by Zehir** [comment]
There is 2 configuration, the rest api for the data and the websocket for the events. The 1006 errors say that the websocket configuration is wrong

**Comment by Mikee1234K** [comment]
Ok that makes sense. Where and how do I see / change the websocket ?

**Comment by Zehir** [comment]
You can see the websocket port in the /config endpoint you wan use the api node or phoscon to get it

**Comment by Mikee1234K** [comment]
Ok I found it. Thanks, seems to be working now. Appreciate your help

**Comment by Zehir** [comment]
No problem
