### ISSUE TITLE
Ikea shader FYRTUR dont show battery charging level

### ISSUE THREAD

**Issue by hoschult** [deconz-community/node-red-contrib-deconz#228]
### Current Behavior

Window blinds does not appear in the drop down menü:

![grafik](https://github.com/deconz-community/node-red-contrib-deconz/assets/20515558/c90562c5-830e-4f70-9768-18dd1099c69d)

### Expected Behavior

roller blinds are defined in deconz and are working also in other nodes like this:

![grafik](https://github.com/deconz-community/node-red-contrib-deconz/assets/20515558/3464f03e-58ae-4e8f-a457-2a3a62a3f3f7)

I would assume that also the battery node would show up in a drop down menu the FYRTUR to be selected so that I can work with the SoC in node red

### Example flow

n/a

### Environment

![grafik](https://github.com/deconz-community/node-red-contrib-deconz/assets/20515558/bd076e69-1fea-4a32-96c4-0b0ac586b244)

![grafik](https://github.com/deconz-community/node-red-contrib-deconz/assets/20515558/9c7decb9-cf36-48f4-a4aa-5dc2f4edd400)

**Comment by Zehir** [comment]
Hello, can you use the api node and get the /config to see if the device is present there

**Comment by hoschult** [comment]
If I connect directly to the conbee II web portal, it is shown up like this:

![grafik](https://github.com/deconz-community/node-red-contrib-deconz/assets/20515558/92b82f2e-1f8a-4d47-b2ee-845462603589)

Within the API node response the device occurs:

![grafik](https://github.com/deconz-community/node-red-contrib-deconz/assets/20515558/7c101e07-dd67-447d-9c4c-4868d29c4009)

**Comment by Zehir** [comment]
This is the battery part of the device, you should have an other one

**Comment by hoschult** [comment]
you're right, the other one part I found under lights:

![grafik](https://github.com/deconz-community/node-red-contrib-deconz/assets/20515558/9acacab0-3e2e-4ee2-963d-f9eace28e244)

**Comment by Zehir** [comment]
Yes for some reason the Windows covering devices are in the light endpoint. So did you find it too in the node ?

**Comment by hoschult** [comment]
no it is not in the node :-(

**Comment by Zehir** [comment]
Could you test with the version `2.3.11` ? It's currently publishing and will be displayed in the node palette in less than 30 minutes

**Comment by hoschult** [comment]
works like charme.... Thx for your great work!!

![grafik](https://github.com/deconz-community/node-red-contrib-deconz/assets/20515558/8bab286f-51ad-402f-9f32-23d952844496)
