### ISSUE TITLE
Error in Utils.js prevents sending requests

### ISSUE THREAD

**Issue by dionmes** [deconz-community/node-red-contrib-deconz#229]
### Current Behavior

Typo in Utils.js prevents sending requests.

`ReferenceError: RED is not defined
    at /home/pi/.node-red/node_modules/node-red-contrib-deconz/src/runtime/Utils.js:31:11
    at new Promise (<anonymous>)
    at Function.getNodeProperty (/home/pi/.node-red/node_modules/node-red-contrib-deconz/src/runtime/Utils.js:30:15)
    at /home/pi/.node-red/node_modules/node-red-contrib-deconz/nodes/out.js:120:35`

The typo is in Utils.js line 31. It references RED.util which should be REDUtil .

**Comment by Zehir** [comment]
Sorry my bad, was a bad copy/paste. Releasing the fix in a few minutes
