### ISSUE TITLE
please delete

### ISSUE THREAD

**Issue by deebeo-blip** [deconz-community/node-red-contrib-deconz#235]
### Example flow

```json
paste your flow here
```

### Environment

- deCONZ plugin version:
- HomeKit plugin version (if used):
- Node-RED version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by Zehir** [comment]
No problem @deebeo-blip , If you need help you can come on the discord https://discord.com/invite/QFhTxqN to talk
