### ISSUE TITLE
Sensor attributes

### ISSUE THREAD

**Issue by mattreim** [deconz-community/node-red-contrib-deconz#237]
### My idea

Hello,
when setting up Home Assistant, I noticed some missing attributes on my sensors. Then I had the idea to implement it with this node-red module. The sensors and attributes can also be seen but I cannot get the values ​​transferred to the devices/deCONZ.

For example:
```
room thermostat: current temperature -> thermostat: externalsensortemp
room thermostat: externalwindowopen -> thermostat: externalwindowopen

```

Thank you

**Comment by Zehir** [comment]
Does it work with the deconz REST API ?

**Comment by mattreim** [comment]
Yes, it works

**Comment by mattreim** [comment]
Here is one of my experimental settings. 
[flows.json](https://github.com/user-attachments/files/17975442/flows.json)

Devices:
bosch radiator thermostat 2 - RBSH-TRV0-ZB-EU
bosch room thermostat 2 - RBSH-RTH0-BAT-ZB-EU

A selection menu for the objects in the output node as in the input would be good.
![Deconz](https://github.com/user-attachments/assets/3ad3e979-105c-41de-ac6b-b834e01f87ec)

**Comment by Zehir** [comment]
You can configure the node like this :
![image](https://github.com/user-attachments/assets/bd1049ce-d1ab-4498-82f9-2d10ca25b06b)

Inject node : 
![image](https://github.com/user-attachments/assets/9939ca53-2a7a-41b3-9136-65b03f325d27)
Output node with single property :
![image](https://github.com/user-attachments/assets/dd67ab3c-7623-4a4f-b60c-b918d52b38a3)

Or like this with multiple property :
![image](https://github.com/user-attachments/assets/f0335996-2b25-4d97-9272-6bbd66e68277)

I am not sure to understand what you are trying to do with the flow you sent me. It's reading the value and send it back to the same device ?

Where do you expect the list like the input node ? Here ?
![image](https://github.com/user-attachments/assets/3d66a38d-f1d0-4f1d-a8c1-6cfdea9aa01c)

**Comment by Zehir** [comment]
The module need to be updated using ESM instead of common js, it's quite a big rework and need some hours to update
