### ISSUE TITLE
Battery node doesn't send which device it is reporting for 

### ISSUE THREAD

**Issue by gvdhoven** [deconz-community/node-red-contrib-deconz#80]
** Describe your idea here**
The battery node currently doesn't report which device it is reporting the battery level for; e.g. as msg.topic or something, but it does know which device is selected by the user in the flow. Now i first have to pass it through a function node before i can use it further in my 'check battery level' flow script. Is this something that can be added?

**Comment by Zehir** [comment]
This is planned in #120 
I think the battery node will be deprecated soon because we can do all the thing with the in node. I will update the battery node to have the same beaviour as the input node

**Comment by Zehir** [comment]
In 2.0 I added the meta property like the input node
