### ISSUE TITLE
Add missing values on sensors

### ISSUE THREAD

**Issue by sushifrick** [deconz-community/node-red-contrib-deconz#81]
I am so glad i found this project and the deconz modules, it helps me a lot to make better use of my smart home devices. Before I was (and still do in parallel) using zigbee2mqtt, but the workflow with node-red-contrib-deconz is just so much more streamlined, great work!

But I do use EUROTRONIC Spirit Zigbee (SPZB0001) Thermostates, that are not fully supported by deconz yet, but one can get them to work with the deconz REST API after doing a basic cluster read in the deconz gui. (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1098).

I can see you made some tests with Thermostates in die examples sections, which work fine to read the Termostat and include it into homekit, bout the output side is still missing - the output node does not even show the thermostat in the device list. Is there an easy way to get them into the device list to steer the thermostat using node-red-contrib-deconz?

Keep up the good work and stay heathy,
Sascha Frick

**Comment by peterguy04** [comment]
I recently link my thermostat upto deconz and my way to solve this for now is for you to use for now, you can use the HTTP request node to send a PUT request directly to the REST api . .  You can use something like the inject node or whatever infront of it containing the payload ie. ```{"mode": "heat","heatsetpoint": 2400} ```

**Comment by sushifrick** [comment]
Hi @peterguy04, thank you for the tip, I will give this a try later this week

**Comment by oywino** [comment]
I have a very similar issue as described by the OP, with my ELKO Thermostat.
What puzzles me is that the node-red-contrib-deconz node shows some of the attributes from the Thermostat but far from all.
If I use the Lovelace Thermostate Card, I get more information there than what node-red-contrib-deconz is able to see. If I use curl to query the Thermostat directly (GET), I see even more information, and if I use deCONZ cluster it shows a ton of attributes.  All of these methods give me more than what node-red-contrib-deconz is able to.  Why is that?  What/where is the limitations that cause node-red-contrib-deconz to show only a few attributes and on what bases were these few selected?  As anexample, both the floor and the air temperature is included, but not the setpoint nor the state of the heater element.  That seems odd.

**Comment by Einstein2150** [comment]
I need the thermostat support too. Meanwhile I try it whit a http-request-node to the DeCONZ-Rest API 😕

**Comment by oywino** [comment]
It would be nice if you all could support the [DEVICE REQUEST] I have filed to get the ELKO Super TR into Phoscon:
https://github.com/dresden-elektronik/phoscon-app-beta/issues/248

Jump in and voice your support.

**Comment by Zehir** [comment]
The issue is because the value you trying to set are in config and not in state. You will be able to do that after #120

**Comment by Zehir** [comment]
Clean up issues, this is now in #130.
