### ISSUE TITLE
Allow using a host name to query for deconz information?

### ISSUE THREAD

**Issue by Ocramius** [deconz-community/node-red-contrib-deconz#90]
I'm currently running `node-red-contrib-deconz` inside a docker swarm setup (probably k3s later on), and the machine hosting deconz can virtually move IP address at all times.

While it is possible to create a virtual network where the IP address is fixed for deconz and node-red, that's a sub-optimal solution that requires some deep knowledge of the network.

Would it be possible to allow querying deconz via hostname, rather than IP address?

Something like `my-deconz.my-domain.tld` instead of entering the IP address.

Thanks in advance!

**Comment by Ocramius** [comment]
I also noticed that the system attempts to do an HTTP request to the deconz from my host machine (the browser that has node-red open), but that host will likely never see deconz, because deconz is behind a load balancer that only forwards requests with a hostname header to the correct backing service (that's because it is one server hosting multiple services on port 80 :D )

I think allowing a hostname should suffice to solve that problem too...

**Comment by Ocramius** [comment]
Sounds like all of this only affects the initial setup.

I did a manual fetch of the API key via:

```sh
docker-compose exec node-red curl -X POST --data '{"devicetype":"Node-red"}' http://my-deconz-hostname-here/api
```

After this, entering a hostname seems to work in general :+1:

**Comment by killeriq** [comment]
is this related to this issue also? 
![image](https://user-images.githubusercontent.com/39062891/96751177-2a125500-13cd-11eb-9d3e-91e97fc2abbd.png)

**Comment by Ocramius** [comment]
Yep, precisely :-)

**Comment by killeriq** [comment]
just got suggested on deConz discord channel how to do it automatically

Click here to "Authenticate app"
![image](https://user-images.githubusercontent.com/39062891/96754339-72cc0d00-13d1-11eb-990a-4710c7453354.png)

Then in NodeRed "Get Settings"
![image](https://user-images.githubusercontent.com/39062891/96754421-91320880-13d1-11eb-8b81-80585c6c489e.png)

**Comment by Ocramius** [comment]
Yes, that works if you enter an IP address, such as `192.168.1.25`.

Doesn't work in my case, since deconz is a "moving target", and can change IP address at any time.

**Comment by killeriq** [comment]
i didnt enter any IP, works will everything EMPTY ;)

**Comment by Ocramius** [comment]
@killeriq yeah, but then if my host moves it's gonna be trouble :D 

Therefore, coupling with hostname would be best.

**Comment by Zehir** [comment]
> i didnt enter any IP, works will everything EMPTY ;)

It's worked because the deconz announce himslef on https://phoscon.de/discover and he fetch all the settings there.

**Comment by Zehir** [comment]
If you set the domain it's working too. Just don't forget to click on `Authenticate App` in Phoscon and then press Get Settings.

Maybe the issue is inside your container. Probably he can't resolve the name.


![screen_ha_local](https://user-images.githubusercontent.com/845225/108239619-615dfc00-714a-11eb-8f83-0e24d05894e1.PNG)

**Comment by Ocramius** [comment]
> Maybe the issue is inside your container. Probably he can't resolve the name.

Service is accessible both via public URI and via DNS wildcard record, and resolves with the default docker DNS (which seems to be using `8.8.8.8` from here)

**Comment by Zehir** [comment]
Can you make sure that `my-deconz.my-domain.tld` resolv to your container ip ? It's a public or private IP ?

**Comment by Ocramius** [comment]
It should be accessible even for y'all: see https://deconz.home.ocrami.us/

**Comment by Zehir** [comment]
Did you add some nat rules in your router to forward the API and Websocket port back to the internal IP of your deconz container ?
Because the requests are sent to the public adress and not the internal ip address of your container.

**Comment by Ocramius** [comment]
Here's some debugging (and by the way, please don't feel obliged to chase my hunt for this bug: I'm super-glad that somebody is doing maintenance in first place!):

```sh
docker-compose exec node-red.home.ocrami.us bash
bash-5.0$ ping deconz.home.ocrami.us
PING deconz.home.ocrami.us (172.23.0.4) 56(84) bytes of data.
64 bytes from docker_deconz.home.ocrami.us_1.docker_default (172.23.0.4): icmp_seq=1 ttl=64 time=0.068 ms
```

As you can see, that's using the internal docker network. HTTP seems to work:

```
bash-5.0$ curl deconz.home.ocrami.us | head -n 10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30172  100 30172    0     0  3273k      0 --:--:-- --:--:-- --:--:-- 3273k
<!DOCTYPE HTML>
<html>
<head>
    <title>Wireless Light Control</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=0, maximum-scale=1.0">
	<link href="bootstrap/css/bootstrap.min.css?chksum9780999" rel="stylesheet">
	<link href="bootstrap/css/bootstrap-responsive.min.css?chksum1478198" rel="stylesheet">
	<link href="style.css?chksum762730" rel="stylesheet" type="text/css">
```

Don't really know how to verify `ws://`, but note that as per https://github.com/Mimiix/node-red-contrib-deconz/issues/90#issuecomment-695054624, manual configuration works (and events flow through / are received by node-red, if the node uses `ws://`)

**Comment by Zehir** [comment]
For the test the ws with this :
`wscat -c "ws://deconz.home.ocrami.us:8081"`
Just check the port of your websocket.
What is the result of this ?
`docker-compose exec node-red curl -X POST --data '{"devicetype":"Node-red"}' http://deconz.home.ocrami.us/api`
Can you test by creating a new server in node-red deconz configuration node and using `deconz.home.ocrami.us` as IP address, setting the ports and click on Get Settings ?

**Comment by Ocramius** [comment]
Ok, so 8081 is weird/unexpected :D 

In fact, according to https://github.com/marthoc/docker-deconz/tree/bde74e771c61ee73f20a6d913b7debdfc7e6759b#command-line-options: 

 > Uses host networking mode for proper uPNP functionality; by default, the web UIs and REST API listen on port 80 and the websockets service listens on port 443. If these ports conflict with other services on your host, you can change them through the environment variables DECONZ_WEB_PORT and DECONZ_WS_PORT described below.

Tried it on the container running `node-red`, and it works with port `443`:

```sh
ash-4.3# docker-compose exec node-red.home.ocrami.us bash
bash-5.0$ npx wscat -c "ws://deconz.home.ocrami.us:8081"
npx: installed 9 in 3.837s
error: connect ECONNREFUSED 172.23.0.4:8081
> bash-5.0$ npx wscat -c "ws://deconz.home.ocrami.us:81"
npx: installed 9 in 3.754s
error: connect ECONNREFUSED 172.23.0.4:81
> bash-5.0$ npx wscat -c "ws://deconz.home.ocrami.us:443"
npx: installed 9 in 3.889s
Connected (press CTRL+C to quit)
```

The `curl` command works as expected:

```
ash-4.3# docker-compose exec node-red.home.ocrami.us curl -X POST --data '{"devicetype":"Node-red"}' http://deconz.home.ocrami.us/api
[{"error":{"address":"/","description":"link button not pressed","type":101}}]
```

That's what I initially did at https://github.com/Mimiix/node-red-contrib-deconz/issues/90#issuecomment-695054624 (cURL manual authentication).

Perhaps this package expects port 8081 by default?

**Comment by Zehir** [comment]
No 8081 it the default port in the Home Assistant integration, try with 443 instead, or try getting the /config using the rest api and use the port labeled `websocketport`

**Comment by Ocramius** [comment]
Yeah, as I mentioned above, `443` works:

```
> bash-5.0$ npx wscat -c "ws://deconz.home.ocrami.us:443"
npx: installed 9 in 3.889s
```

**Comment by Zehir** [comment]
![screen_deconz](https://user-images.githubusercontent.com/845225/108261564-18b33c80-7164-11eb-89b8-7f657c2239e6.PNG)
Can you try these settings and press `Get Settings` just after pressing Authenticate App in Phoscon ?

**Comment by Ocramius** [comment]
Trying that, it produces: 
<img width="291" alt="Capture" src="https://user-images.githubusercontent.com/154256/109082480-5f74d980-7704-11eb-9998-e7221413fd0b.PNG">

Looking at the errors, it seems like it's a security issue within the browser, since the request is attempted client-side:

```
Blocked loading mixed active content “http://deconz.home.ocrami.us/api” vendor.js:2:82612
```

**Comment by Zehir** [comment]
oh yes I see, it's because he try to connect to the api in http and your are in https.
I got the same result with a similar setup;

`Mixed Content: The page at 'https://xxxxxxx/hassio/ingress/a0d7b954_nodered' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://192.168.x.x:y/api'. This request has been blocked; the content must be served over HTTPS.`

I fix that we need to do requests from the node-red server and not from the user computer.

**Comment by Ocramius** [comment]
> To fix that we need to do requests from the node-red server and not from the user computer.

That would probably cut it, thanks! Sorry it took so long to find something so trivial :|

**Comment by Zehir** [comment]
Yas that make sens to have Node-Red do that server side because he could be on a external network. For now Deconz do not support HTTPS / WSS so let see what we can do for that.
There is already a server setting to `Use secured SSL connection` but it's seems it's just for the Web Socket but it's can't work. I think I will add one to enable / disable http on api request in case some one is using a proxy

**Comment by Zehir** [comment]
I tried a thing in my home asisstant setup, I disabled the port forwarding. In HA, node-red and deconz run in docker containers. They are on the same network. We can setup some port forwarding to nat on the host ip (local ip) but they can communicate with their own local ip address in 172.16.x.x. So I will update the discovery process to save the local ip of the container and not the local ip of the host.
It's working but I have some error, he display the devices as not reachable. I need to look more into that

**Comment by Ocramius** [comment]
> So I will update the discovery process to save the local ip of the container and not the local ip of the host.

Reminder to not save IP addresses please: those change all the time :D

**Comment by Zehir** [comment]
> > So I will update the discovery process to save the local ip of the container and not the local ip of the host.
> 
> Reminder to not save IP addresses please: those change all the time :D

Yes save the dns if there is one but sometime there is not ptr avaliable

**Comment by Zehir** [comment]
Now the discovery process save the domain name if avaliable. It's avaliable in beta `2.0.0-beta.17`

**Comment by Ocramius** [comment]
Awesome, thank you so much! 💪
