### ISSUE TITLE
Selection of Device from message

### ISSUE THREAD

**Issue by MartinTerp** [deconz-community/node-red-contrib-deconz#91]
Hi

Is it possible to parse (json?) data to the out node so you can dynamically select device/brightness etc. ?

e.g. something like this would be nice:
{"value":25, "data":{"device":"spot_light_1", "command":"brightness" }}

**Comment by Zehir** [comment]
If you set a device name in the query he will have to first do a get request to get his ID.
I think the accepted values will be numerical for device ID and a string to query the Device Name ID but what to do with duplicate name ?
Maybe add some regex and limit.

**Comment by Zehir** [comment]
This is planned in #120 
You can check the draft version of how this will work https://github.com/deconz-community/node-red-contrib-deconz/wiki/Device-queries
