### ISSUE TITLE
Out Node add a status message "last message + timestamp"

### ISSUE THREAD

**Issue by ACrazyConcept** [deconz-community/node-red-contrib-deconz#97]
Could a "last message + timestamp" label be added?
Something like this one from a home-assistant node. But many other nodes have something similar. I feel like it's missing, in particular for the deconz-out node.

![image](https://user-images.githubusercontent.com/36438756/99148815-30bd8080-268a-11eb-89ba-5f6db827e87d.png)

**Comment by Zehir** [comment]
Sorry I can't figure out how to clean up this mess with the commits.

**Comment by Zehir** [comment]
You can now do that in the beta version `2.0.0-beta.16` by using the jsonata status in the node setting.
```
"called at: " & $moment().format('MMM DD, hh:mm')
```
The jsonata editor in the test tab will display this error : `Attempted to invoke a non-function` but it's [expected](https://discourse.nodered.org/t/using-moment-in-change-node-jsonata-test-results-in-an-error/37995/3), the moment library is not loaded in the browser.
