### ISSUE TITLE
Send config to sensors

### ISSUE THREAD

**Issue by MrksHfmn** [deconz-community/node-red-contrib-deconz#98]
Unfortunately I cannot send data to my device (thermostat). I can request data, but I cannot send any. When setting the values i can only select lamps. Am I doing something wrong?

[Screenshot In Node](https://ibb.co/DgMQ2SQ)
[Screenshot Out Node](https://ibb.co/r5fFXs8)

**Comment by Einstein2150** [comment]
Sensors are not supported yet. You have to write the value (i.e. the targetheatingpoint) directly over the REST-API to deCONZ:
`msg.url: http://<IP>:80/api/<APIKEY>/sensors/<SENSORID>/config
msg.method: PUT
msg.payload: {"heatsetpoint":<TEMP>}
`
You need a HTTP-Request-Node for this...

**Comment by Zehir** [comment]
This is planned in #120

**Comment by Zehir** [comment]
Clean up issues, this is now in #130.
