### ISSUE TITLE
Add out node result output

### ISSUE THREAD

**Issue by DDDanny** [deconz-community/node-red-contrib-deconz#99]
I kindly ask you to consider in a futore realse that the output-node will have the result of the siwtch.
It happens in 10% of the cases to me that the switiching ist noch exectuted as expected...
Should I switch in the meanwhile to a plain REST-call, because I expect that I'll get the response HTTP 200 response or an error there?
Hardware used: conbee II and switching a OSRAM Smart+ Plug with a "yellow connection" routed over a "green" connection.

**Comment by Zehir** [comment]
This is planned in #120 
The output node will return the result of the api request but that don't mean that the zigbee request was successfull. I think it's planned in the new api but we don't expect it before long time
